name: actions
run-name: BaltaevTimur is running rk2_3
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: config example
        run: cmake -H. -B ${{github.workspace}}/build
      - name: config example
        run: cmake --build ${{github.workspace}}/build
